# Generated by Django 4.1.6 on 2023-02-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="techology", new_name="technology",
        ),
    ]
